### ISSUE TITLE
Package install error

### ISSUE THREAD

**Issue by djKooks** [LeapMind/tf_onnx#1]
Hello,
I tried to install via pip yesterday, but it shows bug like below.
```
(venv) kwangin$ pip install tf-onnx
Collecting tf-onnx
  Could not find a version that satisfies the requirement tf-onnx (from versions: )
No matching distribution found for tf-onnx
```
Tested python version is 2.7 and 3.5.
Is there some problem?

Thanks.

**Comment by Hiroshi123** [comment]
Hi, 

I have removed its archives a couple of days ago on pypi. 
I am afraid to say this module has no longer been provided as an open source software for some reasons at least from what I know.

**Comment by djKooks** [comment]
@Hiroshi123 Okay, thanks!
How about make this as private, or make a comment in README?

Thanks.
